export const GET_SINGLE_VALIDASI_REQUEST = "GET_SINGLE_VALIDASI_REQUEST";
export const GET_SINGLE_VALIDASI_SUCCESS = "GET_SINGLE_VALIDASI_SUCCESS";
export const GET_SINGLE_VALIDASI_ERROR = "GET_SINGLE_VALIDASI_ERROR";