export const PENGAJUAN_SINGLE_REQUEST = "PENGAJUAN_SINGLE_REQUEST";
export const PENGAJUAN_SINGLE_SUCCESS = "PENGAJUAN_SINGLE_SUCCESS";
export const PENGAJUAN_SINGLE_ERROR = "PENGAJUAN_SINGLE_ERROR";
