export const GET_ADMIN_PROFILE_REQUEST = "GET_ADMIN_PROFILE_REQUEST";
export const GET_ADMIN_PROFILE_SUCCESS = "GET_ADMIN_PROFILE_SUCCESS";
export const GET_ADMIN_PROFILE_ERROR = "GET_ADMIN_PROFILE_ERROR";